# Force HTTPS except /health for Elastic Beanstalk health checks.
set $redirect_to_https 0;

if ($http_x_forwarded_proto != "https") {
  set $redirect_to_https 1;
}

if ($uri = "/health") {
  set $redirect_to_https 0;
}

if ($redirect_to_https = 1) {
  return 301 https://$host$request_uri;
}
